apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-diff-reporter-config
  namespace: argocd
data:
  config.yaml: |
    global:
      storageDir: /data
    server:
      addr: 0.0.0.0:8080
    webhook:
      repositories:
        - owner: trolleksii
          repo: k8s-argo-apps
    log:
      level: info
      format: json
    tracing:
      endpoint: tempo.observability.svc:4318
      version: v1.0
    argocd:
      namespace: argocd
    workers:
      gitWorker:
        fileGlobs: ["system/manifests/argoapps/*.yaml"]
      githubChecks:
        uiBaseUrl: https://diff.trollabs.com
