apiVersion: v1
kind: ServiceAccount
metadata:
  name: argocd-diff-reporter
  namespace: argocd
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: argocd-diff-reporter
rules:
- apiGroups: [""]
  resources: ["secrets", "configmaps"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: argocd-diff-reporter
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: argocd-diff-reporter
subjects:
- kind: ServiceAccount
  name: argocd-diff-reporter
  namespace: argocd
