apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
  name: argocd-diff-reporter
  namespace: argocd
spec:
  dataFrom:
  - extract:
      conversionStrategy: Default
      decodingStrategy: None
      key: argocd-diff-reporter
      metadataPolicy: None
      nullBytePolicy: Ignore
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: secrets
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    name: argocd-diff-reporter
