name: CI

on:
  push:
    branches:
      - main
    paths:
      - '**/*.go'
      - .github/workflows/ci.yml

defaults:
  run:
    shell: bash

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - run: go test ./... -race -coverprofile=coverage.out

      - run: go tool cover -func=coverage.out

      - run: go test ./... -tags=integration -race -coverprofile=integration.out

      - run: go tool cover -func=integration.out

  build:
    name: Build container image
    runs-on: ubuntu-latest
    needs: test
    permissions:
      contents: read
      id-token: write
      packages: write
    outputs:
      tag: steps.get-tag.outputs.tag
    steps:
      - uses: actions/checkout@v6

      - uses: docker/setup-buildx-action@v4
        with:
          platforms: linux/amd64 #,linux/arm64

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v4
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v4
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Prep metadata
        id: meta
        uses: docker/metadata-action@v6
        with:
          images: |-
            name=trolleksii/argocd-diff-reporter
            name=ghcr.io/trolleksii/argocd-diff-reporter
          tags: |-
            type=sha
            type=raw,value=latest

      - name: Build and Push
        uses: docker/build-push-action@v7
        with:
          context: ./
          file: ./Dockerfile
          push: true
          platforms: linux/amd64 #,linux/arm64
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha,scope=main
          cache-to: type=gha,scope=main,mode=max

      - id: get-tag
        run: |
          tag=$(echo {{ steps.meta.outputs.tags }} | grep sha- | cut -d : -f 2 | uniq)
          echo "tag=${tag}" | tee -a $GITHUB_OUTPUT

  deploy:
    name: Deploy to k8s
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v6
        with:
          repository: trolleksii/k8s-argo-apps
          ref: main
          path: k8s
          ssh-key: "${{ secrets.K8S_DEPLOY_KEY }}"

      - name: Bump image tag
        run: |
          cd k8s
          yq -P -i e '.spec.source.images[0].newTag ] "${{ needs.build.outputs.tag }}"' system/manifests/argoapps/argocd-diff-reporter.yaml
          git config --global user.email 'ci@trollabs.com'
          git config --global user.name 'ci automation'
          git add system/manifests/argoapps/argocd-diff-reporter.yaml
          git commit -m "bump argocd-diff-reporter image tag"
          git push -u origin main
